version: "3.9"
services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multifinance
    ports:
      - "5432:5432"
